/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import controller.RentalService;
import model.Kendaraan;
import model.db_rentalKendaraan;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
/**
 *
 * @author Asus
 */
public class AdminCRUDCarGUI extends javax.swing.JFrame {
    private RentalService rentalService;
    /**
     * Creates new form AdminCRUDCarGUI
     */
    public AdminCRUDCarGUI(RentalService rentalService) {
        
        this.rentalService = rentalService;
        initComponents();
        clearText();
        loadCarList();
        setLocationRelativeTo(null);
    }
    
    private void loadCarList() {
        DefaultTableModel model = new DefaultTableModel();

        // Menambahkan kolom pada tabel
        model.addColumn("ID");
        model.addColumn("Car Name");
        model.addColumn("Capacity");
        model.addColumn("Brand");
        model.addColumn("Rental Price");
        model.addColumn("Status");

        // Mengambil data kendaraan langsung dari database
        try {
            // Membuka koneksi ke database
            Connection conn = db_rentalKendaraan.getConnection();
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT * FROM mobil");

            // Mengambil data dari ResultSet dan menambahkannya ke model tabel
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("id"),
                    rs.getString("nama_mobil"),
                    rs.getString("kapasitas"),
                    rs.getString("merek"),
                    rs.getString("harga_sewa"),
                    rs.getString("status")
                });
            }

            // Menetapkan model pada jTable1
            jTable1.setModel(model);

            // Menutup koneksi setelah selesai
            conn.close();
        } catch (Exception e) {
            // Menampilkan pesan kesalahan jika gagal mengambil data
            JOptionPane.showMessageDialog(null, "Gagal memuat data!");
            e.printStackTrace();
        }
    }
    
    private void clearText() {
        // Kosongkan semua text field
        TxCarName.setText("");
        TxPricePHours1.setText("");
        TxBrand.setText("");
        TxPricePHours.setText("");  // Pastikan text field untuk harga juga dibersihkan
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TabelListMobil = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        BtBack = new javax.swing.JButton();
        TxPricePHours = new javax.swing.JTextField();
        BtEdit = new javax.swing.JButton();
        TxBrand = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        BtRefresh = new javax.swing.JButton();
        BtDelete = new javax.swing.JButton();
        BtCreate = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TxCarName = new javax.swing.JTextField();
        TxPricePHours1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TabelListMobil.setViewportView(jTable1);

        getContentPane().add(TabelListMobil, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 480, 150));

        BtBack.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        BtBack.setText("Back");
        BtBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtBackActionPerformed(evt);
            }
        });
        getContentPane().add(BtBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 420, 90, -1));

        TxPricePHours.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        TxPricePHours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxPricePHoursActionPerformed(evt);
            }
        });
        getContentPane().add(TxPricePHours, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, 140, -1));

        BtEdit.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        BtEdit.setText("Edit");
        BtEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtEditActionPerformed(evt);
            }
        });
        getContentPane().add(BtEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 90, -1));

        TxBrand.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        TxBrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxBrandActionPerformed(evt);
            }
        });
        getContentPane().add(TxBrand, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, 140, -1));

        jLabel8.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Brand");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, -1, -1));

        BtRefresh.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        BtRefresh.setText("Refresh");
        BtRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtRefreshActionPerformed(evt);
            }
        });
        getContentPane().add(BtRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 240, 90, -1));

        BtDelete.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        BtDelete.setText("Delete");
        BtDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(BtDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, 90, -1));

        BtCreate.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        BtCreate.setText("Create");
        BtCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCreateActionPerformed(evt);
            }
        });
        getContentPane().add(BtCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 90, -1));

        jLabel5.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Price per Hour");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, -1, -1));

        jLabel6.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Car Name");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, -1, -1));

        TxCarName.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        TxCarName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxCarNameActionPerformed(evt);
            }
        });
        getContentPane().add(TxCarName, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, 140, -1));

        TxPricePHours1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        TxPricePHours1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxPricePHours1ActionPerformed(evt);
            }
        });
        getContentPane().add(TxPricePHours1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, 140, -1));

        jLabel7.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Seats");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, -1, -1));

        jLabel2.setFont(new java.awt.Font("Montserrat Black", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Car Data");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, -1, -1));

        jLabel4.setFont(new java.awt.Font("Montserrat Black", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("RentCarPro");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/AdminCrud.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxCarNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxCarNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxCarNameActionPerformed

    private void TxPricePHoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxPricePHoursActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxPricePHoursActionPerformed

    private void BtCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCreateActionPerformed
        String namaMobil = TxCarName.getText();
        String kapasitas = TxPricePHours1.getText();
        String merek = TxBrand.getText();
        double harga = Double.parseDouble(TxPricePHours.getText());
        String status = "Available"; // Anda bisa menentukan status sesuai keinginan

        Kendaraan kendaraan = new Kendaraan(0, namaMobil, kapasitas, merek, harga, status);
        rentalService.createCar(kendaraan);
        loadCarList();
        clearText();
    }//GEN-LAST:event_BtCreateActionPerformed

    private void BtBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtBackActionPerformed
        new AdminMenuGUI(rentalService).setVisible(rootPaneCheckingEnabled);
        this.dispose();
    }//GEN-LAST:event_BtBackActionPerformed

    private void BtEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtEditActionPerformed
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow != -1) {
            int id = (int) jTable1.getValueAt(selectedRow, 0);
            String namaMobil = TxCarName.getText();
            String kapasitas = TxPricePHours1.getText();
            String merek = TxBrand.getText();
            double harga;
            try {
                harga = Double.parseDouble(TxPricePHours.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Invalid price value.");
                return; // Exit the method if there's an error in parsing the price
            }
            String status = "Available"; // Tentukan status baru jika perlu

            Kendaraan kendaraan = new Kendaraan(id, namaMobil, kapasitas, merek, harga, status);
            rentalService.updateCar(kendaraan);
            loadCarList();
            clearText();
        } else {
            JOptionPane.showMessageDialog(this, "Please select a car to edit.");
        }
    }//GEN-LAST:event_BtEditActionPerformed

    private void BtRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtRefreshActionPerformed
        loadCarList();
    }//GEN-LAST:event_BtRefreshActionPerformed

    private void TxPricePHours1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxPricePHours1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxPricePHours1ActionPerformed

    private void TxBrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxBrandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxBrandActionPerformed

    private void BtDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtDeleteActionPerformed
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow != -1) {
            int id = (int) jTable1.getValueAt(selectedRow, 0);
            rentalService.deleteCar(id);
            loadCarList();
            clearText();
        } else {
            JOptionPane.showMessageDialog(this, "Please select a car to delete.");
        }
    }//GEN-LAST:event_BtDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RentalService rentalService = new RentalService();
                new LoginGUI(rentalService).setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtBack;
    private javax.swing.JButton BtCreate;
    private javax.swing.JButton BtDelete;
    private javax.swing.JButton BtEdit;
    private javax.swing.JButton BtRefresh;
    private javax.swing.JScrollPane TabelListMobil;
    private javax.swing.JTextField TxBrand;
    private javax.swing.JTextField TxCarName;
    private javax.swing.JTextField TxPricePHours;
    private javax.swing.JTextField TxPricePHours1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
