/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import controller.RentalService;

/**
 *
 * @author Asus
 */
public class AdminMenuGUI extends javax.swing.JFrame {
    private RentalService rentalService;

    /**
     * Creates new form AdminMenu
     */
    public AdminMenuGUI(RentalService rentalService) {
        this.rentalService = rentalService;
        initComponents();
        setLocationRelativeTo(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Logout = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        BtMobilAdmin = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        BtTransAdmin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logout.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        Logout.setText("Log Out");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });
        getContentPane().add(Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 410, 90, -1));

        jLabel7.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Welcome, Admin!");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, -1, -1));

        BtMobilAdmin.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        BtMobilAdmin.setText("Car");
        BtMobilAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtMobilAdminActionPerformed(evt);
            }
        });
        getContentPane().add(BtMobilAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, -1, -1));

        jLabel2.setFont(new java.awt.Font("Montserrat Black", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("RentCarPro");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, -1, -1));

        BtTransAdmin.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        BtTransAdmin.setText("Transaction");
        BtTransAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtTransAdminActionPerformed(evt);
            }
        });
        getContentPane().add(BtTransAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 310, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/admin menu.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtMobilAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtMobilAdminActionPerformed
        new AdminCRUDCarGUI(rentalService).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtMobilAdminActionPerformed

    private void BtTransAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtTransAdminActionPerformed
        new AdminManageTransGUI(rentalService).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtTransAdminActionPerformed

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        new LoginGUI(rentalService).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        // Membuat objek RentalService
        RentalService rentalService = new RentalService(); // Pastikan objek rentalService diinisialisasi terlebih dahulu

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // Membuka AdminMenuGUI dengan RentalService yang telah dibuat
                new AdminMenuGUI(rentalService).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtMobilAdmin;
    private javax.swing.JButton BtTransAdmin;
    private javax.swing.JButton Logout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
