/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import controller.RentalService;
import model.Kendaraan;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.List;
/**
 *
 * @author Asus
 */
public class CarCustGUI extends javax.swing.JFrame {
    private RentalService rentalService;
    /**
     * Creates new form CarCustGUI
     */
    public CarCustGUI(RentalService rentalService) {
        this.rentalService = rentalService;
        initComponents();
        setLocationRelativeTo(null);
        loadCarList();
    }

    private void loadCarList() {
        // Tambahkan kolom "ID" pada tabel
        DefaultTableModel model = new DefaultTableModel(new Object[]{"ID", "Car Name", "Capacity", "Brand", "Rental Price", "Status"}, 0);

        // Ambil daftar kendaraan
        List<Kendaraan> daftarKendaraan = rentalService.getDaftarKendaraan();
        for (Kendaraan kendaraan : daftarKendaraan) {
            // Tambahkan data kendaraan ke model tabel
            model.addRow(new Object[]{
                kendaraan.getId(),         // ID kendaraan
                kendaraan.getNamaMobil(),       // Nama kendaraan
                kendaraan.getKapasitas(),  // Kapasitas
                kendaraan.getMerek(),      // Merek kendaraan
                kendaraan.getHarga(),      // Harga sewa
                kendaraan.getStatus()      // Status
            });
        }

        // Set model tabel
        jTable1.setModel(model);
    }

    private void updateTable(List<Kendaraan> kendaraanList) {
        // Tambahkan kolom "ID" pada tabel
        DefaultTableModel model = new DefaultTableModel(new Object[]{"ID", "Car Name", "Capacity", "Brand", "Rental Price", "Status"}, 0);

        for (Kendaraan kendaraan : kendaraanList) {
            model.addRow(new Object[]{
                kendaraan.getId(),         // ID kendaraan
                kendaraan.getNamaMobil(),       // Nama kendaraan
                kendaraan.getKapasitas(),  // Kapasitas
                kendaraan.getMerek(),      // Merek kendaraan
                kendaraan.getHarga(),      // Harga
                kendaraan.getStatus()      // Status
            });
        }

        // Set model ke jTable1
        jTable1.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        BtTranMobil = new javax.swing.JButton();
        BtCariMobil = new javax.swing.JButton();
        TabelListMobil = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        CbSortingListMobil = new javax.swing.JComboBox<>();
        TxCariMobil = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtBack.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        BtBack.setText("Back");
        BtBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtBackActionPerformed(evt);
            }
        });
        getContentPane().add(BtBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, -1, -1));

        jLabel2.setFont(new java.awt.Font("Montserrat Black", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("List Car");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, -1, -1));

        BtTranMobil.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        BtTranMobil.setText("Create Transaction");
        BtTranMobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtTranMobilActionPerformed(evt);
            }
        });
        getContentPane().add(BtTranMobil, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 410, -1, -1));

        BtCariMobil.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        BtCariMobil.setText("Search");
        BtCariMobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCariMobilActionPerformed(evt);
            }
        });
        getContentPane().add(BtCariMobil, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 130, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TabelListMobil.setViewportView(jTable1);

        getContentPane().add(TabelListMobil, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 620, 250));

        jLabel3.setFont(new java.awt.Font("Montserrat Black", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("RentCarPro");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, -1, -1));

        CbSortingListMobil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Car Name", "Seats" }));
        CbSortingListMobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbSortingListMobilActionPerformed(evt);
            }
        });
        getContentPane().add(CbSortingListMobil, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, -1, -1));

        TxCariMobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxCariMobilActionPerformed(evt);
            }
        });
        getContentPane().add(TxCariMobil, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 330, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/gui trans mobil - Copy.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtTranMobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtTranMobilActionPerformed
        new TransCarGUI(rentalService).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtTranMobilActionPerformed

    private void BtBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtBackActionPerformed
        new CustMenuGUI(rentalService).setVisible(rootPaneCheckingEnabled);
        this.dispose();
    }//GEN-LAST:event_BtBackActionPerformed

    private void TxCariMobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxCariMobilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxCariMobilActionPerformed

    private void CbSortingListMobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbSortingListMobilActionPerformed
        // Ambil filter dari ComboBox
        String selectedFilter = (String) CbSortingListMobil.getSelectedItem();

        // Ambil daftar kendaraan yang sudah disortir
        List<Kendaraan> sortedCars = rentalService.sortKendaraan(selectedFilter);

        // Tampilkan kendaraan yang sudah disortir dalam tabel
        updateTable(sortedCars);
    }//GEN-LAST:event_CbSortingListMobilActionPerformed

    private void BtCariMobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCariMobilActionPerformed
        // Ambil nilai filter dari ComboBox
        String selectedFilter = (String) CbSortingListMobil.getSelectedItem();
        // Ambil keyword dari TextField
        String keyword = TxCariMobil.getText();

        // Cek apakah keyword kosong
        if (keyword.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a keyword for the search.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Lakukan pencarian dan mendapatkan hasil
        String hasilPencarian = rentalService.searchCar(selectedFilter, keyword);

        // Set model tabel dengan hasil pencarian
        DefaultTableModel model = new DefaultTableModel(new Object[]{"ID", "Car Name", "Capacity", "Brand", "Price", "Status"}, 0);

        if (!hasilPencarian.equals("No vehicles found with the given criteria.")) {
            String[] results = hasilPencarian.split("\n\n");
            for (String result : results) {
                String[] details = result.split("\n");
                if (details.length >= 6) { // Perhatikan 6 kolom, termasuk ID
                    String id = details[0].replace("ID: ", "");
                    String carName = details[1].replace("Car Name: ", "");
                    String capacity = details[2].replace("Capacity: ", "");
                    String brand = details[3].replace("Brand: ", "");
                    String price = details[4].replace("Price: ", "");
                    String status = details[5].replace("Status: ", "");
                    model.addRow(new Object[]{id, carName, capacity, brand, price, status});
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, hasilPencarian, "Search Result", JOptionPane.INFORMATION_MESSAGE);
        }

        // Set model ke jTable1 untuk menampilkan hasil pencarian
        jTable1.setModel(model);
    }//GEN-LAST:event_BtCariMobilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RentalService rentalService = new RentalService(); // Instance sementara
                new CarCustGUI(rentalService).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtBack;
    private javax.swing.JButton BtCariMobil;
    private javax.swing.JButton BtTranMobil;
    private javax.swing.JComboBox<String> CbSortingListMobil;
    private javax.swing.JScrollPane TabelListMobil;
    private javax.swing.JTextField TxCariMobil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
