/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import controller.RentalService; 
import javax.swing.JOptionPane; 
import model.Kendaraan;

/**
 *
 * @author Asus
 */
public class CustMenuGUI extends javax.swing.JFrame {
    private RentalService rentalService;
    /**
     * Creates new form PilihKendaraanGUI
     */
    public CustMenuGUI(RentalService rentalService) {
        this.rentalService = rentalService;
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtTopUp = new javax.swing.JButton();
        BtMobil1 = new javax.swing.JButton();
        Logout = new javax.swing.JButton();
        BtTrans = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 500));
        setMinimumSize(new java.awt.Dimension(800, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtTopUp.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        BtTopUp.setText("Top Up");
        BtTopUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtTopUpActionPerformed(evt);
            }
        });
        getContentPane().add(BtTopUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 310, 90, -1));

        BtMobil1.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        BtMobil1.setText("Car");
        BtMobil1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtMobil1ActionPerformed(evt);
            }
        });
        getContentPane().add(BtMobil1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, 90, -1));

        Logout.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        Logout.setText("Log Out");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });
        getContentPane().add(Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 410, 90, -1));

        BtTrans.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        BtTrans.setText("Transaction");
        BtTrans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtTransActionPerformed(evt);
            }
        });
        getContentPane().add(BtTrans, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 400, 140, -1));

        jLabel8.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Select Menu");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, -1, -1));

        jLabel2.setFont(new java.awt.Font("Montserrat Black", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("RentCarPro");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/custmenu - Copy.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtTopUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtTopUpActionPerformed
        new TopUpCustGUI(rentalService).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtTopUpActionPerformed

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        new LoginGUI(rentalService).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LogoutActionPerformed

    private void BtTransActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtTransActionPerformed
        new TransCustGUI(rentalService).setVisible(true);
        this.dispose(); // Tutup CustMenuGUI
    }//GEN-LAST:event_BtTransActionPerformed

    private void BtMobil1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtMobil1ActionPerformed
        new CarCustGUI(rentalService).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtMobil1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // Membuat instance RentalService
                RentalService rentalService = new RentalService();
                new CustMenuGUI(rentalService).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtMobil1;
    private javax.swing.JButton BtTopUp;
    private javax.swing.JButton BtTrans;
    private javax.swing.JButton Logout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
