/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import controller.RentalService;
import model.Customer;
import model.Pengguna;
import javax.swing.JOptionPane;
import java.util.regex.Pattern;
/**
 *
 * @author Asus
 */
public class RegisterGUI extends javax.swing.JFrame {
    private RentalService rentalService; 
    /**
     * Creates new form RegisterGUI
     */
    public RegisterGUI(RentalService rentalService) {
        this.rentalService = rentalService;
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtBack = new javax.swing.JButton();
        TxUsername1 = new javax.swing.JTextField();
        TxPw = new javax.swing.JPasswordField();
        TxEmail = new javax.swing.JTextField();
        TxAddress = new javax.swing.JTextField();
        Next = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtBack.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        BtBack.setText("Back");
        BtBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtBackActionPerformed(evt);
            }
        });
        getContentPane().add(BtBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, -1, -1));

        TxUsername1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxUsername1ActionPerformed(evt);
            }
        });
        getContentPane().add(TxUsername1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 260, -1));

        TxPw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxPwActionPerformed(evt);
            }
        });
        getContentPane().add(TxPw, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 260, -1));

        TxEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxEmailActionPerformed(evt);
            }
        });
        getContentPane().add(TxEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 260, -1));

        TxAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxAddressActionPerformed(evt);
            }
        });
        getContentPane().add(TxAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 260, -1));

        Next.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        Next.setText("Next");
        Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextActionPerformed(evt);
            }
        });
        getContentPane().add(Next, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 420, 90, -1));

        jLabel8.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Email");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        jLabel10.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Address");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        jLabel6.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Password");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        jLabel3.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Username");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        jLabel2.setFont(new java.awt.Font("Montserrat Black", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("RentCarPro");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, -1, -1));

        jLabel4.setFont(new java.awt.Font("Montserrat", 0, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Complete the information below to create a new account.");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/gui regis.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxUsername1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxUsername1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxUsername1ActionPerformed

    private void TxEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxEmailActionPerformed

    private void TxAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxAddressActionPerformed

    private void TxPwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxPwActionPerformed

    }//GEN-LAST:event_TxPwActionPerformed

    private boolean isValidEmail(String email) {
        String emailRegex = "^[A-Za-z0-9+_.-]+@(.+)$";
        return Pattern.matches(emailRegex, email);
    }
    
    private void NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextActionPerformed
        String username = TxUsername1.getText();
        String password = new String(TxPw.getPassword());
        String email = TxEmail.getText();
        String address = TxAddress.getText();

        double saldo = 0.0;  // Saldo untuk customer baru adalah 0

        // Validasi input
        if (username.isEmpty() || password.isEmpty() || email.isEmpty() || address.isEmpty()) {
            JOptionPane.showMessageDialog(this, "All fields must be filled in!", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (!isValidEmail(email)) {
            JOptionPane.showMessageDialog(this, "Invalid email format!", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            // Panggil method register untuk menambahkan pengguna
            boolean success = rentalService.register(username, password, "customer", address, email, saldo);

            if (success) {
                JOptionPane.showMessageDialog(this, "Account created successfully!");
                new LoginGUI(rentalService).setVisible(true);  // Pindah ke LoginGUI setelah registrasi
                this.dispose();  // Menutup RegisterGUI
            } else {
                JOptionPane.showMessageDialog(this, "Failed to create account. Username already taken.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_NextActionPerformed

    private void BtBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtBackActionPerformed
        new LoginGUI(rentalService).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            RentalService rentalService = new RentalService(); // Inisialisasi RentalService
            new RegisterGUI(rentalService).setVisible(true); // Pass rentalService ke RegisterGUI
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtBack;
    private javax.swing.JButton Next;
    private javax.swing.JTextField TxAddress;
    private javax.swing.JTextField TxEmail;
    private javax.swing.JPasswordField TxPw;
    private javax.swing.JTextField TxUsername1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
