/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import model.Customer;
import controller.RentalService;
/**
 *
 * @author Asus
 */
public class TopUpCustGUI extends javax.swing.JFrame {
    private RentalService rentalService;
    /**
     * Creates new form TopUpCustGUI
     */
    public TopUpCustGUI(RentalService rentalService) {
        this.rentalService = rentalService;
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        Jr1000k = new javax.swing.JRadioButton();
        Jr800k = new javax.swing.JRadioButton();
        Jr400k = new javax.swing.JRadioButton();
        Jr600k = new javax.swing.JRadioButton();
        BtConfirmTopup = new javax.swing.JButton();
        BtBack = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup1.add(Jr1000k);
        Jr1000k.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 14)); // NOI18N
        Jr1000k.setForeground(new java.awt.Color(0, 0, 0));
        Jr1000k.setText("1,000k");
        Jr1000k.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jr1000kActionPerformed(evt);
            }
        });
        getContentPane().add(Jr1000k, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, -1, -1));

        buttonGroup1.add(Jr800k);
        Jr800k.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 14)); // NOI18N
        Jr800k.setForeground(new java.awt.Color(0, 0, 0));
        Jr800k.setText("800k");
        Jr800k.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jr800kActionPerformed(evt);
            }
        });
        getContentPane().add(Jr800k, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, -1, -1));

        buttonGroup1.add(Jr400k);
        Jr400k.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 14)); // NOI18N
        Jr400k.setForeground(new java.awt.Color(0, 0, 0));
        Jr400k.setText("400k");
        Jr400k.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jr400kActionPerformed(evt);
            }
        });
        getContentPane().add(Jr400k, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, -1, -1));

        buttonGroup1.add(Jr600k);
        Jr600k.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 14)); // NOI18N
        Jr600k.setForeground(new java.awt.Color(0, 0, 0));
        Jr600k.setText("600k");
        Jr600k.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jr600kActionPerformed(evt);
            }
        });
        getContentPane().add(Jr600k, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, -1, -1));

        BtConfirmTopup.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        BtConfirmTopup.setText("Confirm");
        BtConfirmTopup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtConfirmTopupActionPerformed(evt);
            }
        });
        getContentPane().add(BtConfirmTopup, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 350, -1, -1));

        BtBack.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        BtBack.setText("Back");
        BtBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtBackActionPerformed(evt);
            }
        });
        getContentPane().add(BtBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, -1, -1));

        jLabel8.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Select Top Up Amount");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, -1, -1));

        jLabel2.setFont(new java.awt.Font("Montserrat Black", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("RentCarPro");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/topup.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Jr1000kActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jr1000kActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jr1000kActionPerformed

    private void Jr400kActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jr400kActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jr400kActionPerformed

    private void Jr800kActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jr800kActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jr800kActionPerformed

    private void Jr600kActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jr600kActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jr600kActionPerformed

    private void BtBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtBackActionPerformed
        new CustMenuGUI(rentalService).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtBackActionPerformed

    private void BtConfirmTopupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtConfirmTopupActionPerformed
        int topUpAmount = 0;

        if (Jr400k.isSelected()) {
            topUpAmount = 400000;
        } else if (Jr600k.isSelected()) {
            topUpAmount = 600000;
        } else if (Jr800k.isSelected()) {
            topUpAmount = 800000;
        } else if (Jr1000k.isSelected()) {
            topUpAmount = 1000000;
        }

        if (topUpAmount == 0) {
            JOptionPane.showMessageDialog(this, "Pilih jumlah top-up terlebih dahulu.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            Customer currentUser = rentalService.getCurrentUser();
            if (currentUser != null) {
                double currentSaldo = currentUser.getSaldo();
                double updatedSaldo = currentSaldo + topUpAmount;

                rentalService.updateSaldo(currentUser.getId(), topUpAmount);
                currentUser.setSaldo(updatedSaldo);  // Mengupdate saldo di objek customer

                JOptionPane.showMessageDialog(this, "Top-up berhasil! Saldo Anda sekarang: Rp " + updatedSaldo);
                new CustMenuGUI(rentalService).setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Gagal mendapatkan data pengguna.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {  // Tangani semua exception
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat top-up.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BtConfirmTopupActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // Anda harus menginisialisasi RentalService sebelum memanggil GUI ini
                RentalService rentalService = new RentalService();
                new TopUpCustGUI(rentalService).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtBack;
    private javax.swing.JButton BtConfirmTopup;
    private javax.swing.JRadioButton Jr1000k;
    private javax.swing.JRadioButton Jr400k;
    private javax.swing.JRadioButton Jr600k;
    private javax.swing.JRadioButton Jr800k;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
