/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import controller.RentalService;
import javax.swing.JOptionPane;
import model.Kendaraan;
/**
 *
 * @author Asus
 */
public class TransCarGUI extends javax.swing.JFrame {
    private RentalService rentalService;
    /**
     * Creates new form TransaksiMobilGUI
     */
    public TransCarGUI(RentalService rentalService) {
        this.rentalService = rentalService;
        initComponents();
        setLocationRelativeTo(null);
        loadCarIDs(); // Load car IDs to the combo box
    }
    
    private void loadCarIDs() {
        // Clear existing items
        Cbidmobil.removeAllItems();
        // Fetch available cars
        for (Kendaraan kendaraan : rentalService.getAvailableCars()) {
            if (kendaraan != null) { // Tambahkan validasi
                Cbidmobil.addItem(kendaraan.getId() + " - " + kendaraan.getNamaMobil());
            }
        }
    }

    private void populateCarDetails() {
        String selectedCar = (String) Cbidmobil.getSelectedItem();
        if (selectedCar != null && !selectedCar.isEmpty()) {
            try {
                int carId = Integer.parseInt(selectedCar.split(" - ")[0]);
                Kendaraan kendaraan = rentalService.getCarDetails(carId);
                if (kendaraan != null) { // Validasi jika kendaraan tidak null
                    TxCarName.setText(kendaraan.getNamaMobil());
                    TxBrand.setText(kendaraan.getMerek());
                    TxCapacity.setText(kendaraan.getKapasitas());
                    TxPricepHour.setText(String.valueOf(kendaraan.getHarga()));
                } else {
                    JOptionPane.showMessageDialog(this, "Car details not found!");
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Invalid car ID format.");
            }
        }
    }
    
    private void calculateTotalPrice() {
        try {
            int pricePerDay = Integer.parseInt(TxPricepHour.getText());
            String selectedDuration = (String) CbHour.getSelectedItem();
            int days = 0;

            switch (selectedDuration) {
                case "1 Days":
                    days = 1;
                    break;
                case "3 Days":
                    days = 3;
                    break;
                case "7 Days":
                    days = 7;
                    break;
                case "14 Days":
                    days = 14;
                    break;
                case "30 Days":
                    days = 30;
                    break;
            }

            int totalPrice = pricePerDay * days;
            TxTotalPrice.setText(String.valueOf(totalPrice));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid price format.");
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtListCars = new javax.swing.JButton();
        BtConfirm = new javax.swing.JButton();
        TxBrand = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        TxTotalPrice = new javax.swing.JTextField();
        TxPricepHour = new javax.swing.JTextField();
        CbHour = new javax.swing.JComboBox<>();
        Cbidmobil = new javax.swing.JComboBox<>();
        TxCarName = new javax.swing.JTextField();
        TxCapacity = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtListCars.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        BtListCars.setText("List Car");
        BtListCars.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtListCarsActionPerformed(evt);
            }
        });
        getContentPane().add(BtListCars, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 370, 120, -1));

        BtConfirm.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        BtConfirm.setText("Confirm");
        BtConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtConfirmActionPerformed(evt);
            }
        });
        getContentPane().add(BtConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 370, 120, -1));

        TxBrand.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        TxBrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxBrandActionPerformed(evt);
            }
        });
        getContentPane().add(TxBrand, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, 140, -1));

        jLabel5.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Capacity");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, -1, -1));

        jLabel3.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Brand");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, -1, -1));

        jLabel7.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("ID Car");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, -1, -1));

        jLabel8.setFont(new java.awt.Font("Montserrat", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Hour");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, -1, -1));

        jLabel10.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Total Price");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, -1, -1));

        TxTotalPrice.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        TxTotalPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxTotalPriceActionPerformed(evt);
            }
        });
        getContentPane().add(TxTotalPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 340, 140, -1));

        TxPricepHour.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        TxPricepHour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxPricepHourActionPerformed(evt);
            }
        });
        getContentPane().add(TxPricepHour, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 270, 140, -1));

        CbHour.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        CbHour.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 Days", "3 Days", "7 Days", "14 Days", "30 Days" }));
        CbHour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbHourActionPerformed(evt);
            }
        });
        getContentPane().add(CbHour, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, 140, -1));

        Cbidmobil.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        Cbidmobil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Cbidmobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbidmobilActionPerformed(evt);
            }
        });
        getContentPane().add(Cbidmobil, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, 140, 20));

        TxCarName.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        TxCarName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxCarNameActionPerformed(evt);
            }
        });
        getContentPane().add(TxCarName, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, 140, -1));

        TxCapacity.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        TxCapacity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxCapacityActionPerformed(evt);
            }
        });
        getContentPane().add(TxCapacity, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, 140, -1));

        jLabel9.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Price per Hours");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, -1, -1));

        jLabel6.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Car Name");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, -1, -1));

        jLabel2.setFont(new java.awt.Font("Montserrat Black", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Rent Car");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, -1, -1));

        jLabel4.setFont(new java.awt.Font("Montserrat Black", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("RentCarPro");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/gui trans mobil.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxBrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxBrandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxBrandActionPerformed

    private void BtConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtConfirmActionPerformed
        try {
            String selectedCar = (String) Cbidmobil.getSelectedItem();
            int carId = Integer.parseInt(selectedCar.split(" - ")[0]);
            String selectedDuration = (String) CbHour.getSelectedItem();
            int totalPrice = Integer.parseInt(TxTotalPrice.getText());

            // Call RentalService to create a rental transaction
            boolean success = rentalService.rentCar(carId, selectedDuration, totalPrice);
            if (success) {
                JOptionPane.showMessageDialog(this, "Car rental confirmed!");
            } else {
                JOptionPane.showMessageDialog(this, "Failed to confirm rental.");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please fill in all the fields correctly.");
        }
    }//GEN-LAST:event_BtConfirmActionPerformed

    private void BtListCarsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtListCarsActionPerformed
        new CarCustGUI(rentalService).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtListCarsActionPerformed

    private void TxCarNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxCarNameActionPerformed
        TxCarName.setEnabled(false);
    }//GEN-LAST:event_TxCarNameActionPerformed

    private void TxCapacityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxCapacityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxCapacityActionPerformed

    private void CbidmobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbidmobilActionPerformed
        populateCarDetails();
    }//GEN-LAST:event_CbidmobilActionPerformed

    private void TxPricepHourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxPricepHourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxPricepHourActionPerformed

    private void CbHourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbHourActionPerformed
        calculateTotalPrice();
    }//GEN-LAST:event_CbHourActionPerformed

    private void TxTotalPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxTotalPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxTotalPriceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            RentalService rentalService = new RentalService();
            new TransCarGUI(rentalService).setVisible(true);
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtConfirm;
    private javax.swing.JButton BtListCars;
    private javax.swing.JComboBox<String> CbHour;
    private javax.swing.JComboBox<String> Cbidmobil;
    private javax.swing.JTextField TxBrand;
    private javax.swing.JTextField TxCapacity;
    private javax.swing.JTextField TxCarName;
    private javax.swing.JTextField TxPricepHour;
    private javax.swing.JTextField TxTotalPrice;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
